/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.market.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 07-08-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class AddcartAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession(true);
		String id=request.getParameter("id");
		
		ActionForward forward = null; 
		ArrayList<goods> goods = (ArrayList)session.getAttribute("goodslist");
		ArrayList<goods> shopcar = null;
		goods g=null;
		for (int i=0;i<goods.size();i++){
	    	 g= (goods)goods.get(i);
	    	   if ((g.getDataid()).equals(id)){
	    	       break;
	    	      }
	    	   }
		int amount=g.getBuyamount();
		amount++;
        g.setBuyamount(amount);
		
		if((ArrayList)session.getAttribute("shopcar")==null)
		{
		shopcar = new ArrayList();
		 shopcar.add(g);
		
		
		}
	
		else
		{
		shopcar=(ArrayList)session.getAttribute("shopcar");
		
		   if(shopcar.isEmpty())
		      {
		         shopcar.add(g);
		         
		      }		        
		 else
		       { 
			     if(amount==1){
			        shopcar.add(g);	 
			    	 
			     }
			     else{
			       for (int j=0;j<shopcar.size();j++)
			              {
			    	       goods shopgoods= (goods)shopcar.get(j);
			    	        if ((shopgoods.getDataid()).equals(id))
			    	          {   shopcar.set(j, g);
			    	             break;
			    	          }
			    	            
			              }
		            
		        
		          
		       }     
		 }
         
     }
		
		 session.setAttribute("shopcar",shopcar);    
		 forward = mapping.findForward("car");
		return forward;
	}
}