/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.market.struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-07-2009
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="get" path="/get.jsp"
 */
public class DisplayAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		ArrayList<goods> goodslist=new ArrayList<goods>();
		

		String strSql= "SELECT * FROM goods";
		Connection con = null;   
		Statement st = null;   
		ResultSet rs=null;
		ActionForward forward = null; 
		try{   
			  //get the datasource
			  DataSource dataSource = getDataSource(request,"datasource");  
			  //get connection
			  con = dataSource.getConnection();   
			  //execute query
			  st = con.createStatement();    
			  rs = st.executeQuery(strSql);
			  while(rs.next())
			  {
				  goods g=new goods();
				  g.setName(rs.getString("name"));
				  g.setPrice(rs.getString("price"));
				  g.setAmount(rs.getString("amount"));
				  g.setCategory(rs.getString("category"));
				  g.setSeller(rs.getString("seller"));
				  g.setDataid(rs.getString("id"));
				  goodslist.add(g);
			  }
			  
			  HttpSession session = request.getSession();
			  session.setAttribute("goodslist", goodslist);
			  forward = mapping.findForward("get");
			  rs.close();
			  st.close();
			  con.close();
			  
			}catch(SQLException e){
				System.out.println(e.getMessage());
			}
		
		
		
		return forward;
	}
}