/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.market.struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.market.struts.form.GetForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-07-2009
 * 
 * XDoclet definition:
 * @struts.action path="/get" name="getForm" input="/get.jsp" scope="request"
 */
public class GetAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetForm getForm = (GetForm) form;// TODO Auto-generated method stub
		
		String name = getForm.getName();
		ArrayList<goods> sgoodslist=new ArrayList<goods>();

		String strSql= "SELECT * FROM goods WHERE name='" + name + "'" ;
		Connection con = null;   
		Statement st = null;   
		ResultSet rs=null;
		ActionForward forward = null; 
		try{   
			  //get the datasource
			  DataSource dataSource = getDataSource(request,"datasource");  
			  //get connection
			  con = dataSource.getConnection();   
			  //execute query
			  st = con.createStatement();    
			  rs = st.executeQuery(strSql);
			  while(rs.next())
			  {
				  goods g=new goods();
				  g.setDataid(rs.getString("id"));				  
				  g.setName(rs.getString("name"));
				  g.setPrice(rs.getString("price"));
				  g.setAmount(rs.getString("amount"));
				  g.setCategory(rs.getString("category"));
				  g.setSeller(rs.getString("seller"));
				  sgoodslist.add(g);
			  }
			  
			  HttpSession session = request.getSession();
			  session.setAttribute("sgoodslist", sgoodslist);

			  forward = mapping.findForward("list");   
		   
		}catch(SQLException e){
			System.out.println(e.getMessage());
		}
		return forward;
	}
	}
