/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.market.struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.market.struts.form.SellForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-02-2008
 * 
 * XDoclet definition:
 * @struts.action path="/user" name="userForm" input="/login.jsp" scope="request"
 */
public class SellAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SellForm SellForm = (SellForm) form;// TODO Auto-generated method stub
  	   
		HttpSession session = request.getSession();
		String name = SellForm.getName();
		int amount = SellForm.getAmount();
		Float price = SellForm.getPrice();
		String seller = (String)session.getAttribute("username");
		String category = SellForm.getCategory();
		String des = SellForm.getDes();
		String strSql = "INSERT INTO goods (name,amount,price,seller,category)values('"+name+"',amount,'"+price+"','"+seller+"','"+category+"')";
		ActionForward forward = null; 
				
		Connection con = null;;   
		Statement st = null;   
		int rsLogon = 0;
		try{   
		  //get the data source
		  DataSource dataSource = getDataSource(request,"datasource");  
		  //get connection
		  con = dataSource.getConnection();   
		  //execute query
		  st = con.createStatement();    
    	  rsLogon = st.executeUpdate(strSql);
		  session.setAttribute("name", name);	
		  String sprice=""+price;
		  session.setAttribute("price", sprice);	
		  String samount=""+amount;
		  session.setAttribute("amount", samount);	
		  session.setAttribute("category", category);	
		     
		}catch(SQLException e){
			System.out.println(e.getMessage());
		}
		
		forward = mapping.findForward("selldetail");
		return forward;
	}
}