/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.market.struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.market.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-02-2008
 * 
 * XDoclet definition:
 * @struts.action path="/user" name="userForm" input="/login.jsp" scope="request"
 */
public class UserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		String username = userForm.getUsername();
		String password = userForm.getPassword();
		String strSql = "select * from userinfo where username='" + username + "'";
		ActionForward forward = null; 
				
		Connection con = null;;   
		Statement st = null;   
		ResultSet rsLogon = null;      
		try{   
		  //get the data source
		  DataSource dataSource = getDataSource(request,"datasource");  
		  //get connection
		  con = dataSource.getConnection();   
		  //execute query
		  st = con.createStatement();    
		  rsLogon = st.executeQuery(strSql);   
		  String dbPassword = null;   
		  if(rsLogon.next()){   
			  dbPassword = rsLogon.getString("password");   
		  }   
		  if(dbPassword == null || !dbPassword.equals(password)){   
			  forward = mapping.findForward("failure");   
		  }else{   
			  HttpSession session = request.getSession();
			  session.setAttribute("username", username);
			  forward = mapping.findForward("welcome");   
		  } 
		}catch(SQLException e){
			System.out.println(e.getMessage());
		}
		return forward;
	}
}