/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.market.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.validator.ValidatorForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-07-2009
 * 
 * XDoclet definition:
 * @struts.form name="sellForm"
 */
public class SellForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** amount property */
	private int amount;

	/** price property */
	private Float price;

	/** seller property */
	private String seller;

	/** category property */
	private String category;

	/** name property */
	private String name;

	/** des property */
	private String des;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = super.validate(mapping, request);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the amount.
	 * @return Float
	 */
	public int getAmount() {
		return amount;
	}

	/** 
	 * Set the amount.
	 * @param amount The amount to set
	 */
	public void setAmount(int amount) {
		this.amount = amount;
	}

	/** 
	 * Returns the price.
	 * @return Float
	 */
	public Float getPrice() {
		return price;
	}

	/** 
	 * Set the price.
	 * @param price The price to set
	 */
	public void setprice(Float price) {
		this.price = price;
	}

	/** 
	 * Returns the seller.
	 * @return String
	 */
	public String getSeller() {
		return seller;
	}

	/** 
	 * Set the seller.
	 * @param seller The seller to set
	 */
	public void setSeller(String seller) {
		this.seller = seller;
	}

	/** 
	 * Returns the category.
	 * @return String
	 */
	public String getCategory() {
		return category;
	}

	/** 
	 * Set the category.
	 * @param category The category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the des.
	 * @return String
	 */
	public String getDes() {
		return des;
	}

	/** 
	 * Set the des.
	 * @param des The des to set
	 */
	public void setDes(String des) {
		this.des = des;
	}
}